### ISSUE TITLE
Recommend changing project name

### ISSUE THREAD

**Issue by josue** [suzuki-shunsuke/flute#20]
Hi, this is a pretty cool testing framework you created and I think the Go community would like it.

However, I **highly recommend** that you change the project name to something else. The word "fagott" strongly resembles the slang word "[faggot](https://en.wikipedia.org/wiki/Faggot_(slang))" which is a very negative connotation in the English language. I would hate for Gophers to ignore your project because of this innocent mistake.

I'm sure you have other awesome names around. 😃

**Comment by suzuki-shunsuke** [comment]
@josue Thank you for your feedback!
I understand. I will change the project name.
I didn't know such a slang.

Thank you again.

**Comment by suzuki-shunsuke** [comment]
I will change the project name to "flute".

**Comment by suzuki-shunsuke** [comment]
I have changed the project name to "flute".
Thank you for your feedback!

**Comment by josue** [comment]
Cool 😃
